@extends('layouts.app')
@section('title', 'Kas dan Pengeluaran')
@section('heading', 'Kas dan Pengeluaran')
@section('content')
<div class="mb-6"><h2 class="text-xl font-black">Buku kas toko</h2><p class="text-sm text-slate-500">Catat pemasukan dan biaya operasional di luar transaksi penjualan.</p></div>
<form class="card mb-6 flex flex-wrap items-end gap-3" method="GET"><div><label class="label">Dari</label><input class="input" type="date" name="from" value="{{ $from }}"></div><div><label class="label">Sampai</label><input class="input" type="date" name="to" value="{{ $to }}"></div><button class="btn-secondary" type="submit">Filter</button></form>
<div class="grid gap-4 sm:grid-cols-3 mb-6"><div class="stat-card"><p class="text-sm text-slate-500">Kas masuk</p><p class="mt-2 text-xl font-black text-emerald-600">Rp {{ number_format($income, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Kas keluar</p><p class="mt-2 text-xl font-black text-red-600">Rp {{ number_format($expense, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Saldo bersih</p><p class="mt-2 text-xl font-black">Rp {{ number_format($income - $expense, 0, ',', '.') }}</p></div></div>
<form class="card mb-6" method="POST" action="{{ route('cash.store') }}">@csrf<div class="grid gap-4 md:grid-cols-4"><div><label class="label">Jenis</label><select class="input" name="type"><option value="expense">Kas keluar</option><option value="income">Kas masuk</option></select></div><div><label class="label">Kategori</label><input class="input" name="category" placeholder="Listrik, transport, dll" required></div><div><label class="label">Nominal</label><input class="input" name="amount" type="number" min="0.01" step="0.01" required></div><div><label class="label">Keterangan</label><input class="input" name="description"></div></div><button class="btn-primary mt-4" type="submit">Simpan Transaksi Kas</button></form>
<div class="card overflow-x-auto p-0"><div class="border-b p-5"><h3 class="font-extrabold">Riwayat buku kas</h3></div><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Tanggal</th><th class="p-4">Jenis</th><th class="p-4">Kategori</th><th class="p-4">Nominal</th><th class="p-4">Keterangan</th><th class="p-4">Petugas</th></tr></thead><tbody>@forelse($transactions as $transaction)<tr class="border-t"><td class="p-4">{{ $transaction->occurred_at->format('d M Y H:i') }}</td><td class="p-4"><span class="rounded-full px-2 py-1 text-xs font-bold {{ $transaction->type === 'income' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700' }}">{{ $transaction->type === 'income' ? 'Masuk' : 'Keluar' }}</span></td><td class="p-4">{{ $transaction->category }}</td><td class="p-4 font-bold">Rp {{ number_format($transaction->amount, 0, ',', '.') }}</td><td class="p-4">{{ $transaction->description ?? '-' }}</td><td class="p-4">{{ $transaction->user->name }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">Belum ada transaksi kas.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $transactions->links() }}</div></div>
@endsection
