@extends('layouts.app')
@section('title', 'Batch dan Kedaluwarsa')
@section('heading', 'Batch & Kedaluwarsa')
@section('content')
<div class="mb-6"><h2 class="text-xl font-black">Pelacakan batch barang</h2><p class="text-sm text-slate-500">Pantau tanggal kedaluwarsa jamu dan dahulukan batch yang paling dekat kedaluwarsa.</p></div>
<div class="grid gap-4 md:grid-cols-3 mb-6"><div class="stat-card"><p class="text-sm text-slate-500">Sudah kedaluwarsa</p><p class="mt-2 text-2xl font-black text-red-600">{{ $expired }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Segera kedaluwarsa</p><p class="mt-2 text-2xl font-black text-amber-600">{{ $soon }}</p><small class="text-slate-500">Dalam {{ $days }} hari</small></div><div class="stat-card"><p class="text-sm text-slate-500">Aturan stok</p><p class="mt-2 text-sm font-semibold text-slate-700">Penjualan memakai batch dengan kedaluwarsa paling dekat.</p></div></div>
<form class="card mb-6 flex flex-wrap items-end gap-3" method="GET"><div class="min-w-[240px] flex-1"><label class="label">Barang</label><select class="input" name="product_id"><option value="">Semua barang</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(request('product_id') == $product->id)>{{ $product->name }}</option>@endforeach</select></div><div><label class="label">Peringatan hari</label><input class="input w-32" type="number" name="days" value="{{ $days }}" min="1" max="365"></div><button class="btn-primary" type="submit">Filter</button></form>
<div class="card overflow-x-auto p-0"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Barang</th><th class="p-4">Batch</th><th class="p-4">Kedaluwarsa</th><th class="p-4">Sisa</th><th class="p-4">Status</th><th class="p-4">Modal</th></tr></thead><tbody>@forelse($batches as $batch)@php($daysLeft=$batch->days_to_expire)<tr class="border-t"><td class="p-4 font-bold">{{ $batch->product->name }}</td><td class="p-4">{{ $batch->batch_number }}</td><td class="p-4">{{ $batch->expires_at?->format('d M Y') ?? '-' }}</td><td class="p-4">{{ $batch->remaining_quantity }}</td><td class="p-4">@if($daysLeft !== null && $daysLeft < 0)<span class="rounded-full bg-red-100 px-2 py-1 text-xs font-bold text-red-700">Expired</span>@elseif($daysLeft !== null && $daysLeft <= $days)<span class="rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-700">{{ $daysLeft }} hari</span>@else<span class="rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold text-emerald-700">Aman</span>@endif</td><td class="p-4">Rp {{ number_format($batch->unit_cost, 0, ',', '.') }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">Belum ada batch dengan stok tersisa.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $batches->links() }}</div></div>
@endsection
