@extends('layouts.app')
@section('title', 'Hutang Supplier')
@section('heading', 'Hutang Supplier')
@section('content')
<div class="mb-6"><h2 class="text-xl font-black">Hutang dan pembayaran supplier</h2><p class="text-sm text-slate-500">Pantau pembelian kredit, jatuh tempo, dan pembayaran yang sudah dilakukan.</p></div>
<div class="grid gap-4 md:grid-cols-2 mb-6"><div class="stat-card"><p class="text-sm text-slate-500">Total hutang berjalan</p><p class="mt-2 text-2xl font-black text-red-600">Rp {{ number_format($totalDebt, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Pembelian belum lunas</p><p class="mt-2 text-2xl font-black">{{ $purchases->count() }}</p></div></div>
<div class="space-y-4 mb-8">@forelse($purchases as $purchase)<div class="card"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-extrabold">{{ $purchase->supplier->name }}</h3><p class="text-sm text-slate-500">{{ $purchase->number }} · {{ $purchase->created_at->format('d M Y') }} · Jatuh tempo {{ $purchase->due_date?->format('d M Y') ?? '-' }}</p></div><div class="text-right"><p class="text-xs text-slate-500">Sisa hutang</p><p class="text-xl font-black text-red-600">Rp {{ number_format($purchase->outstanding, 0, ',', '.') }}</p></div></div><form class="mt-4 flex flex-wrap items-end gap-3 border-t pt-4" method="POST" action="{{ route('supplier-debts.pay', $purchase) }}">@csrf<label class="min-w-[180px] flex-1"><span class="label">Nominal pembayaran</span><input class="input" name="amount" type="number" min="0.01" max="{{ $purchase->outstanding }}" step="0.01" required></label><label><span class="label">Metode</span><select class="input" name="method"><option value="cash">Tunai</option><option value="transfer">Transfer</option><option value="giro">Giro</option></select></label><label class="min-w-[180px] flex-1"><span class="label">Catatan</span><input class="input" name="notes"></label><button class="btn-primary" type="submit">Catat Pembayaran</button></form></div>@empty<div class="card text-center text-slate-500">Tidak ada hutang supplier yang berjalan.</div>@endforelse</div>
<div class="card overflow-x-auto p-0"><div class="border-b p-5"><h3 class="font-extrabold">Riwayat pembayaran</h3></div><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Tanggal</th><th class="p-4">Supplier</th><th class="p-4">Pembelian</th><th class="p-4">Nominal</th><th class="p-4">Metode</th><th class="p-4">Petugas</th></tr></thead><tbody>@forelse($payments as $payment)<tr class="border-t"><td class="p-4">{{ $payment->paid_at->format('d M Y H:i') }}</td><td class="p-4">{{ $payment->supplier->name }}</td><td class="p-4">{{ $payment->purchase?->number ?? '-' }}</td><td class="p-4 font-bold text-emerald-600">Rp {{ number_format($payment->amount, 0, ',', '.') }}</td><td class="p-4">{{ strtoupper($payment->method) }}</td><td class="p-4">{{ $payment->user->name }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">Belum ada pembayaran hutang.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $payments->links() }}</div></div>
@endsection
