@extends('layouts.app')
@section('title', 'Laporan Keuntungan')
@section('heading', 'Laporan Keuntungan')
@section('content')
<form class="card mb-6 flex flex-wrap items-end gap-3" method="GET"><div><label class="label">Dari</label><input class="input" name="from" type="date" value="{{ $from }}"></div><div><label class="label">Sampai</label><input class="input" name="to" type="date" value="{{ $to }}"></div><button class="btn-primary" type="submit">Tampilkan</button></form>
@php($profit = $grossSales - $cost - $returns - $operatingExpense)
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div class="stat-card"><p class="text-sm text-slate-500">Omzet kotor</p><p class="mt-2 text-xl font-black text-emerald-600">Rp {{ number_format($grossSales, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Modal terjual</p><p class="mt-2 text-xl font-black text-red-600">Rp {{ number_format($cost, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Nilai retur</p><p class="mt-2 text-xl font-black text-amber-600">Rp {{ number_format($returns, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Biaya operasional</p><p class="mt-2 text-xl font-black text-red-600">Rp {{ number_format($operatingExpense, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Laba bersih</p><p class="mt-2 text-xl font-black {{ $profit < 0 ? 'text-red-600' : 'text-emerald-600' }}">Rp {{ number_format($profit, 0, ',', '.') }}</p></div></div>
<div class="card mt-6 overflow-x-auto p-0"><div class="border-b p-5"><h3 class="font-extrabold">Rincian transaksi</h3></div><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Invoice</th><th class="p-4">Kasir</th><th class="p-4">Omzet</th><th class="p-4">Modal</th><th class="p-4">Margin</th><th class="p-4">Tanggal</th></tr></thead><tbody>@forelse($sales as $sale)@php($saleCost = $sale->items->sum(fn($item) => (float)($item->product?->buy_price ?? 0) * $item->quantity))<tr class="border-t"><td class="p-4 font-bold">{{ $sale->invoice_number }}</td><td class="p-4">{{ $sale->cashier->name }}</td><td class="p-4">Rp {{ number_format($sale->total, 0, ',', '.') }}</td><td class="p-4">Rp {{ number_format($saleCost, 0, ',', '.') }}</td><td class="p-4 font-bold text-emerald-600">Rp {{ number_format($sale->total - $saleCost, 0, ',', '.') }}</td><td class="p-4">{{ $sale->created_at->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">Belum ada penjualan pada periode ini.</td></tr>@endforelse</tbody></table></div>
@endsection
