<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('suppliers',fn(Blueprint $t)=>[$t->id(),$t->string('name'),$t->string('phone')->nullable(),$t->text('address')->nullable(),$t->timestamps()]);
Schema::create('purchases',fn(Blueprint $t)=>[$t->id(),$t->string('number')->unique(),$t->foreignId('supplier_id')->constrained(),$t->foreignId('user_id')->constrained(),$t->decimal('total',15,2),$t->text('notes')->nullable(),$t->timestamps()]);
Schema::create('purchase_items',fn(Blueprint $t)=>[$t->id(),$t->foreignId('purchase_id')->constrained()->cascadeOnDelete(),$t->foreignId('product_id')->constrained(),$t->string('product_name'),$t->decimal('price',15,2),$t->integer('quantity'),$t->integer('returned_quantity')->default(0),$t->decimal('subtotal',15,2),$t->timestamps()]);
Schema::create('purchase_returns',fn(Blueprint $t)=>[$t->id(),$t->string('number')->unique(),$t->foreignId('purchase_id')->constrained(),$t->foreignId('supplier_id')->constrained(),$t->foreignId('user_id')->constrained(),$t->decimal('total',15,2),$t->text('reason'),$t->timestamps()]);
Schema::create('purchase_return_items',fn(Blueprint $t)=>[$t->id(),$t->foreignId('purchase_return_id')->constrained()->cascadeOnDelete(),$t->foreignId('purchase_item_id')->constrained(),$t->foreignId('product_id')->constrained(),$t->integer('quantity'),$t->decimal('subtotal',15,2),$t->timestamps()]);
Schema::create('sale_returns',fn(Blueprint $t)=>[$t->id(),$t->string('number')->unique(),$t->foreignId('sale_id')->constrained(),$t->foreignId('user_id')->constrained(),$t->decimal('total',15,2),$t->text('reason'),$t->timestamps()]);
Schema::create('sale_return_items',fn(Blueprint $t)=>[$t->id(),$t->foreignId('sale_return_id')->constrained()->cascadeOnDelete(),$t->foreignId('sale_item_id')->constrained(),$t->foreignId('product_id')->constrained(),$t->integer('quantity'),$t->boolean('restock')->default(true),$t->decimal('subtotal',15,2),$t->timestamps()]);
Schema::create('stock_opnames',fn(Blueprint $t)=>[$t->id(),$t->string('number')->unique(),$t->foreignId('user_id')->constrained(),$t->text('notes')->nullable(),$t->timestamps()]);
Schema::create('stock_opname_items',fn(Blueprint $t)=>[$t->id(),$t->foreignId('stock_opname_id')->constrained()->cascadeOnDelete(),$t->foreignId('product_id')->constrained(),$t->integer('system_stock'),$t->integer('physical_stock'),$t->integer('difference'),$t->text('reason')->nullable(),$t->timestamps()]);
} public function down(): void { foreach(['stock_opname_items','stock_opnames','sale_return_items','sale_returns','purchase_return_items','purchase_returns','purchase_items','purchases','suppliers'] as $t)Schema::dropIfExists($t); } };
