@extends('layouts.app')
@section('title', 'Kartu Stok')
@section('heading', 'Kartu Stok')
@section('content')
<div class="mb-6"><h2 class="text-xl font-black">Riwayat pergerakan stok</h2><p class="text-sm text-slate-500">Telusuri stok masuk, keluar, penjualan, retur, dan penyesuaian opname.</p></div>
<div class="grid gap-4 md:grid-cols-3 mb-6"><div class="stat-card"><p class="text-sm text-slate-500">Stok perlu perhatian</p><p class="mt-2 text-2xl font-black text-amber-600">{{ $lowStock->count() }}</p></div><div class="stat-card md:col-span-2"><p class="text-sm text-slate-500">Tips</p><p class="mt-2 text-sm font-semibold text-slate-700">Gunakan filter barang untuk audit satu produk secara lengkap.</p></div></div>
<form class="card mb-6 flex flex-wrap items-end gap-3" method="GET"><div class="min-w-[220px] flex-1"><label class="label">Barang</label><select class="input" name="product_id"><option value="">Semua barang</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected($selected == $product->id)>{{ $product->name }} ({{ $product->code }})</option>@endforeach</select></div><div><label class="label">Pergerakan</label><select class="input" name="movement"><option value="">Semua</option><option value="in" @selected($movement === 'in')>Barang Masuk</option><option value="out" @selected($movement === 'out')>Barang Keluar</option></select></div><div><label class="label">Jenis</label><select class="input" name="type"><option value="">Semua jenis</option><option value="purchase" @selected($type === 'purchase')>Pembelian</option><option value="sale" @selected($type === 'sale')>Penjualan</option><option value="transfer_in" @selected($type === 'transfer_in')>Transfer masuk</option><option value="transfer_out" @selected($type === 'transfer_out')>Transfer keluar</option><option value="outflow" @selected($type === 'outflow')>Pengeluaran barang</option><option value="other_out" @selected($type === 'other_out')>Pengeluaran & retur supplier</option><option value="purchase_return" @selected($type === 'purchase_return')>Retur supplier</option><option value="sale_return" @selected($type === 'sale_return')>Retur penjualan</option><option value="opname" @selected($type === 'opname')>Stock opname</option></select></div><div><label class="label">Dari</label><input class="input" name="from" type="date" value="{{ request('from') }}"></div><div><label class="label">Sampai</label><input class="input" name="to" type="date" value="{{ request('to') }}"></div><button class="btn-primary" type="submit">Filter</button></form>
<div class="card overflow-x-auto p-0"><div class="border-b p-5"><h3 class="font-extrabold">Kartu stok</h3></div><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Tanggal</th><th class="p-4">Barang</th><th class="p-4">Jenis</th><th class="p-4">Perubahan</th><th class="p-4">Saldo dasar</th><th class="p-4">Referensi</th><th class="p-4">Petugas</th></tr></thead><tbody>@forelse($logs as $log)<tr class="border-t"><td class="p-4">{{ $log->created_at->format('d M Y H:i') }}</td><td class="p-4 font-semibold">{{ $log->product->name }}</td><td class="p-4">{{ ucwords(str_replace('_', ' ', $log->type)) }}</td><td class="p-4 font-bold {{ $log->quantity_change < 0 ? 'text-red-600' : 'text-emerald-600' }}">{{ $log->quantity_change > 0 ? '+' : '' }}{{ $log->transaction_quantity ?? abs($log->quantity_change) }} {{ $log->unit_name ?? $log->product->unit }} @if(($log->conversion_quantity ?? 1) > 1)<small class="block font-medium text-slate-400">= {{ $log->quantity_change > 0 ? '+' : '-' }}{{ abs($log->quantity_change) }} {{ $log->product->unit }}</small>@endif</td><td class="p-4">{{ $log->stock_after }} {{ $log->product->unit }}</td><td class="p-4 text-slate-500">{{ $log->reference ?? '-' }}</td><td class="p-4">{{ $log->user?->name ?? '-' }}</td></tr>@empty<tr><td colspan="7" class="p-8 text-center text-slate-500">Belum ada pergerakan stok.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $logs->links() }}</div></div>
@endsection
