@extends('layouts.app')
@section('title', 'Pengeluaran Barang')
@section('heading', 'Pengeluaran Barang')
@section('content')
<div class="mb-6"><h2 class="text-xl font-black">Barang rusak, kadaluarsa, dan pemakaian internal</h2><p class="text-sm text-slate-500">Catat stok keluar yang bukan transaksi penjualan agar saldo persediaan tetap akurat.</p></div>
<form class="card mb-6" method="POST" action="{{ route('outflows.store') }}">@csrf<div class="grid gap-4 md:grid-cols-2"><div><label class="label">Jenis pengeluaran</label><select class="input" name="reason_type" required><option value="rusak">Barang rusak</option><option value="kadaluarsa">Kadaluarsa</option><option value="pemakaian_internal">Pemakaian internal</option><option value="sampel">Sampel</option><option value="bonus">Bonus</option><option value="lainnya">Lainnya</option></select></div><div><label class="label">Catatan</label><input class="input" name="notes" maxlength="500" placeholder="Keterangan tambahan"></div></div><div id="outflow-items" class="mt-4 space-y-2"><div class="outflow-row flex flex-wrap items-end gap-3 rounded-xl bg-slate-50 p-3"><label class="min-w-[220px] flex-1 text-sm font-semibold">Barang<select class="input mt-1" name="items[0][product_id]" required><option value="">Pilih barang</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} · stok {{ $product->stock }}</option>@endforeach</select></label><label class="text-sm font-semibold">Jumlah<input class="input mt-1 w-28" name="items[0][quantity]" type="number" min="1" required></label><button class="remove-row rounded-lg bg-red-100 px-3 py-2 text-sm font-bold text-red-700" type="button">Hapus</button></div></div><div class="mt-4 flex flex-wrap gap-3"><button class="btn-secondary" type="button" id="add-row">＋ Tambah barang</button><button class="btn-primary" type="submit">Simpan Pengeluaran</button></div></form>
<div class="card overflow-x-auto p-0"><div class="border-b p-5"><h3 class="font-extrabold">Riwayat pengeluaran</h3></div><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Nomor</th><th class="p-4">Jenis</th><th class="p-4">Barang</th><th class="p-4">Total qty</th><th class="p-4">Petugas</th><th class="p-4">Tanggal</th></tr></thead><tbody>@forelse($outflows as $outflow)<tr class="border-t"><td class="p-4 font-bold">{{ $outflow->number }}</td><td class="p-4">{{ ucwords(str_replace('_', ' ', $outflow->reason_type)) }}</td><td class="p-4">{{ $outflow->items->pluck('product_name')->join(', ') }}</td><td class="p-4">{{ $outflow->total_qty }}</td><td class="p-4">{{ $outflow->user->name }}</td><td class="p-4">{{ $outflow->created_at->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">Belum ada pengeluaran barang.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $outflows->links() }}</div></div>
<script>let row=1;document.getElementById('add-row').addEventListener('click',()=>{const first=document.querySelector('.outflow-row');const copy=first.cloneNode(true);copy.querySelectorAll('select,input').forEach(el=>{el.name=el.name.replace(/items\[0\]/,'items['+row+']');el.value=''});document.getElementById('outflow-items').appendChild(copy);row++});document.addEventListener('click',e=>{if(e.target.matches('.remove-row')&&document.querySelectorAll('.outflow-row').length>1)e.target.closest('.outflow-row').remove()});</script>
@endsection
