<?php
namespace App\Http\Controllers;
use App\Models\{Brand,Category,Supplier,Unit}; use Illuminate\Http\Request;
class MasterDataController extends Controller {
 public function index(){return view('master.index',['categories'=>Category::latest()->get(),'units'=>Unit::latest()->get(),'brands'=>Brand::latest()->get(),'suppliers'=>Supplier::latest()->get()]);}
 public function store(Request $r,string $type){$map=['categories'=>[Category::class,['name'=>'required|max:80','description'=>'nullable']], 'units'=>[Unit::class,['name'=>'required|max:40','symbol'=>'nullable|max:15']], 'brands'=>[Brand::class,['name'=>'required|max:80','description'=>'nullable']], 'suppliers'=>[Supplier::class,['name'=>'required|max:120','contact_person'=>'nullable|max:100','phone'=>'nullable|max:30','address'=>'nullable','is_active'=>'nullable|boolean']]];abort_unless(isset($map[$type]),404);[$class,$rules]=$map[$type];$data=$r->validate($rules);if(in_array($type,['units','brands','suppliers'],true))$data['is_active']=$r->boolean('is_active');$class::create($data);return back()->with('success','Data master berhasil ditambahkan.');}
 public function update(Request $r,string $type,int $id){$map=['categories'=>Category::class,'units'=>Unit::class,'brands'=>Brand::class,'suppliers'=>Supplier::class];abort_unless(isset($map[$type]),404);$model=$map[$type]::findOrFail($id);$rules=['name'=>'required|max:120'];if($type==='units')$rules['symbol']='nullable|max:15';if(in_array($type,['categories','brands'],true))$rules['description']='nullable';if($type==='suppliers')$rules=['name'=>'required|max:120','contact_person'=>'nullable|max:100','phone'=>'nullable|max:30','address'=>'nullable','is_active'=>'nullable|boolean'];$data=$r->validate($rules);if(in_array($type,['units','brands','suppliers'],true))$data['is_active']=$r->boolean('is_active');$model->update($data);return back()->with('success','Data master berhasil diperbarui.');}
 public function destroy(string $type,int $id){$map=['categories'=>Category::class,'units'=>Unit::class,'brands'=>Brand::class,'suppliers'=>Supplier::class];abort_unless(isset($map[$type]),404);$model=$map[$type]::findOrFail($id);if(method_exists($model,'products')&&$model->products()->exists())return back()->withErrors(['master'=>'Data masih dipakai barang dan tidak dapat dihapus.']);$model->delete();return back()->with('success','Data master dihapus.');}
}
