@extends('layouts.app')
@section('title', 'Modal Pemilik')
@section('heading', 'Modal Pemilik')
@section('content')
<div class="mb-6"><h2 class="text-xl font-black">Modal dan pengambilan pemilik</h2><p class="text-sm text-slate-500">Pisahkan setoran usaha dan pengambilan pemilik dari pendapatan maupun biaya toko.</p></div>
<form class="card mb-6 flex flex-wrap items-end gap-3" method="GET"><div><label class="label">Dari</label><input class="input" name="from" type="date" value="{{ $from }}"></div><div><label class="label">Sampai</label><input class="input" name="to" type="date" value="{{ $to }}"></div><button class="btn-secondary" type="submit">Filter</button></form>
<div class="grid gap-4 sm:grid-cols-3 mb-6"><div class="stat-card"><p class="text-sm text-slate-500">Setoran modal</p><p class="mt-2 text-xl font-black text-emerald-600">Rp {{ number_format($capitalIn, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Pengambilan modal</p><p class="mt-2 text-xl font-black text-red-600">Rp {{ number_format($withdrawal, 0, ',', '.') }}</p></div><div class="stat-card"><p class="text-sm text-slate-500">Perubahan modal periode</p><p class="mt-2 text-xl font-black">Rp {{ number_format($capitalIn - $withdrawal, 0, ',', '.') }}</p></div></div>
<form class="card mb-6" method="POST" action="{{ route('owner-capital.store') }}">@csrf<div class="grid gap-4 md:grid-cols-4"><div><label class="label">Jenis</label><select class="input" name="type"><option value="capital_in">Setoran modal</option><option value="capital_withdrawal">Pengambilan modal</option></select></div><div><label class="label">Nominal</label><input class="input" name="amount" type="number" min="0.01" step="0.01" required></div><div><label class="label">Tanggal</label><input class="input" name="occurred_at" type="datetime-local" value="{{ now()->format('Y-m-d\\TH:i') }}" required></div><div><label class="label">Keterangan</label><input class="input" name="description" maxlength="255" placeholder="Contoh: modal awal toko"></div></div><button class="btn-primary mt-4" type="submit">Simpan Modal</button></form>
<div class="card overflow-x-auto p-0"><div class="border-b p-5"><h3 class="font-extrabold">Riwayat modal</h3></div><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Tanggal</th><th class="p-4">Jenis</th><th class="p-4">Nominal</th><th class="p-4">Keterangan</th><th class="p-4">Petugas</th></tr></thead><tbody>@forelse($transactions as $transaction)<tr class="border-t"><td class="p-4">{{ $transaction->occurred_at->format('d M Y H:i') }}</td><td class="p-4">{{ $transaction->type === 'capital_in' ? 'Setoran modal' : 'Pengambilan modal' }}</td><td class="p-4 font-bold">Rp {{ number_format($transaction->amount, 0, ',', '.') }}</td><td class="p-4">{{ $transaction->description ?: '-' }}</td><td class="p-4">{{ $transaction->user->name }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">Belum ada transaksi modal.</td></tr>@endforelse</tbody></table><div class="border-t p-4">{{ $transactions->links() }}</div></div>
@endsection
