@extends('layouts.app')

@section('title', 'Transfer Stok')
@section('heading', 'Transfer Stok Gudang')

@section('content')
<div class="mb-6"><h2 class="text-xl font-black">Distribusi dari {{ $sourceStore->name }}</h2><p class="mt-1 text-sm text-slate-500">Transfer tidak dihitung sebagai penjualan. Stok gudang berkurang dan stok toko tujuan bertambah dengan batch serta tanggal kedaluwarsa tetap terbawa.</p></div>
<form method="POST" action="{{ route('stock-transfers.store') }}" class="card">
    @csrf
    <div class="grid gap-4 md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]"><div><label class="label">Kirim ke toko *</label><select class="input" name="destination_store_id" required><option value="">Pilih toko tujuan</option>@foreach($destinations as $store)<option value="{{ $store->id }}">{{ $store->name }}</option>@endforeach</select></div><div><label class="label">Catatan</label><input class="input" name="notes" placeholder="Contoh: kirim untuk stok akhir pekan"></div></div>
    <div id="transfer-lines" class="mt-5 space-y-3"></div>
    <button type="button" class="btn-muted mt-3" id="add-transfer-line">Tambah Barang</button>
    <div class="mt-5 flex justify-end"><button class="btn-primary">Proses Transfer</button></div>
</form>
<div class="card mt-6 overflow-x-auto p-0"><div class="border-b p-5"><h3 class="font-extrabold">Riwayat Transfer</h3></div><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Nomor</th><th class="p-4">Tujuan</th><th class="p-4">Barang</th><th class="p-4">Petugas</th><th class="p-4">Tanggal</th></tr></thead><tbody>@forelse($transfers as $transfer)<tr class="border-t align-top"><td class="p-4 font-bold">{{ $transfer->number }}</td><td class="p-4">{{ $transfer->destinationStore->name }}</td><td class="p-4">@foreach($transfer->items as $item)<div>{{ $item->product_name }} — {{ $item->quantity }} {{ $item->unit_name }} <small class="text-slate-400">({{ $item->base_quantity }} stok dasar)</small></div>@endforeach</td><td class="p-4">{{ $transfer->user->name }}</td><td class="p-4 text-slate-500">{{ $transfer->transferred_at->format('d M Y H:i') }}</td></tr>@empty<tr><td colspan="5" class="p-8 text-center text-slate-500">Belum ada transfer dari gudang.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $transfers->links() }}</div>
<script>
const catalog=@json($products->mapWithKeys(fn ($product)=>[$product->id=>['name'=>$product->name,'unit'=>$product->unit,'stock'=>$product->stock,'packagings'=>$product->packagings->map(fn($packaging)=>['id'=>$packaging->id,'name'=>$packaging->name,'conversion'=>$packaging->conversion_quantity])->values()]));
const lines=document.getElementById('transfer-lines');let index=0;const productOptions='<option value="">Pilih barang</option>'+Object.entries(catalog).map(([id,product])=>`<option value="${id}">${product.name} (stok ${product.stock} ${product.unit})</option>`).join('');function packagingOptions(productId){const product=catalog[productId];if(!product)return '<option value="">Pilih barang dulu</option>';return `<option value="">${product.unit} (1 ${product.unit})</option>`+product.packagings.map(row=>`<option value="${row.id}">${row.name} (${row.conversion} ${product.unit})</option>`).join('')}function addLine(){const lineIndex=index++;const line=document.createElement('div');line.className='rounded-xl bg-slate-50 p-3';line.innerHTML=`<div class="grid gap-2 md:grid-cols-[minmax(0,2fr)_minmax(0,1.2fr)_140px_auto]"><select class="input product" name="items[${lineIndex}][product_id]" required>${productOptions}</select><select class="input packaging" name="items[${lineIndex}][product_packaging_id]"></select><input class="input" name="items[${lineIndex}][quantity]" type="number" min="1" placeholder="Jumlah" required><button type="button" class="btn-muted remove">Hapus</button></div><p class="mt-2 note text-xs text-slate-500"></p>`;const product=line.querySelector('.product'),packaging=line.querySelector('.packaging');function sync(){packaging.innerHTML=packagingOptions(product.value);const info=catalog[product.value];line.querySelector('.note').textContent=info?'Stok gudang dihitung dalam '+info.unit+'. Pilih karton agar jumlah otomatis dikonversi.':''}product.onchange=sync;line.querySelector('.remove').onclick=()=>line.remove();lines.appendChild(line);sync()}addLine();document.getElementById('add-transfer-line').onclick=addLine;
</script>
@endsection
